import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  marathi: {
    code: "mr",
    name: "मराठी (Marathi)",
    speechLang: "mr-IN",
    navHome: "Home",
    navBlog: "Blog",
    navCommunity: "Community",
    navWeather: "Weather",
    navMarket: "Market Tracker",
    navLanguages: "Languages",
    btnDiseasePredict: "Disease Predict",
    btnFertilization: "Fertilization",
    btnRecommend: "Recommend",
    heroBadge: "AI कृषी डॉक्टर • मोफत पीक रोग तपासणी",
    heroTitle1: "Protect Your Crops from",
    heroTitle2: "Pests & Diseases Instantly.",
    heroSubtitle: "तुमच्या पिकांच्या पानांचा फोटो काढा. आमचे AI काही सेकंदात रोगाचे अचूक निदान करून घरगुती व जैविक उपाय आणि औषधांची माहिती मराठीत देईल.",
    step1Title: "1. Take Photo",
    step1Desc: "फोटो काढा",
    step2Title: "2. AI Scans",
    step2Desc: "रोग निदान",
    step3Title: "3. Get Cure",
    step3Desc: "उपाय मिळवा",
    btnScanDisease: "Scan Crop Disease Now",
    btnCropAdvisory: "Crop Advisory",
    shortDisease: "Disease Doctor",
    shortDiseaseDesc: "पीक रोग निदान",
    shortCrop: "Crop Recommendation",
    shortCropDesc: "योग्य पीक सल्ला",
    shortFertilizer: "Fertilizer Advisory",
    shortFertilizerDesc: "योग्य खतांचे प्रमाण",
    shortWeather: "Weather & Market",
    shortWeatherDesc: "हवामान आणि बाजारभाव",
    featBadge: "🌾 विशेषतः शेतकऱ्यांसाठी डिझाइन केलेले",
    featHeading: "पिकांचे रक्षण करा आणि भरघोस उत्पन्न मिळवा",
    featSubheading: "तुमच्या स्मार्टफोनवरून शेतीतील दैनंदिन अडचणी सोडवण्यासाठी सोपी, अचूक आणि उपयुक्त साधने.",
    f1Title: "Instant Plant Disease Detection",
    f1Sub: "झटपट पीक रोग निदान",
    f1Desc: "तुमच्या पिकांच्या पानांचा फोटो काढा. Gemini Vision AI बुरशीजन्य, जिवाणूजन्य आणि कीटकांच्या हल्ल्यांचे काही सेकंदात निदान करते.",
    f2Title: "Precision Fertilizer Dosage",
    f2Sub: "योग्य खतांचे प्रमाण व सल्ला",
    f2Desc: "अनावश्यक रासायनिक खर्च टाळा. तुमच्या मातीचा प्रकार आणि पिकासाठी योग्य N-P-K खतांचे आणि सेंद्रिय खतांचे अचूक प्रमाण मिळवा.",
    f3Title: "Soil-Smart Crop Advisory",
    f3Sub: "मातीनुसार योग्य पीक शिफारस",
    f3Desc: "मशीन लर्निंग मॉडेल्स तुमच्या मातीतील घटक आणि पावसाचे विश्लेषण करून अधिक उत्पादन देणाऱ्या पिकांची शिफारस करतात.",
    f4Title: "Multilingual Voice Assistant",
    f4Sub: "व्हॉईस कृषी सहाय्यक",
    f4Desc: "तुमच्या फोनवर बोलून शेतीविषयक प्रश्न विचारा आणि टाईप न करता बोलून उत्तरे ऐका."
  },
  kannada: {
    code: "kn",
    name: "ಕನ್ನಡ (Kannada)",
    speechLang: "kn-IN",
    navHome: "Home",
    navBlog: "Blog",
    navCommunity: "Community",
    navWeather: "Weather",
    navMarket: "Market Tracker",
    navLanguages: "Languages",
    btnDiseasePredict: "Disease Predict",
    btnFertilization: "Fertilization",
    btnRecommend: "Recommend",
    heroBadge: "AI ಕೃಷಿ ವೈದ್ಯ • ಉಚಿತ ಬೆಳೆ ರೋಗ ತಪಾಸಣೆ",
    heroTitle1: "Protect Your Crops from",
    heroTitle2: "Pests & Diseases Instantly.",
    heroSubtitle: "ನಿಮ್ಮ ಬೆಳೆಗಳ ಎಲೆಗಳ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ. ನಮ್ಮ AI ಕೆಲವೇ ಸೆಕೆಂಡುಗಳಲ್ಲಿ ರೋಗವನ್ನು ಪತ್ತೆಹಚ್ಚಿ ಪರಿಹಾರ ಮತ್ತು ಸಾವಯವ ಔಷಧಿಗಳನ್ನು ಕನ್ನಡದಲ್ಲಿ ನೀಡುತ್ತದೆ.",
    step1Title: "1. Take Photo",
    step1Desc: "ಚಿತ್ರ ತೆಗೆಯಿರಿ",
    step2Title: "2. AI Scans",
    step2Desc: "ರೋಗ ಪತ್ತೆ",
    step3Title: "3. Get Cure",
    step3Desc: "ಪರಿಹಾರ ಪಡೆಯಿರಿ",
    btnScanDisease: "Scan Crop Disease Now",
    btnCropAdvisory: "Crop Advisory",
    shortDisease: "Disease Doctor",
    shortDiseaseDesc: "ಬೆಳೆ ರೋಗ ಪತ್ತೆ",
    shortCrop: "Crop Recommendation",
    shortCropDesc: "ಸೂಕ್ತ ಬೆಳೆ ಸಲಹೆ",
    shortFertilizer: "Fertilizer Advisory",
    shortFertilizerDesc: "ಗೊಬ್ಬರ ಪ್ರಮಾಣ",
    shortWeather: "Weather & Market",
    shortWeatherDesc: "ಹವಾಮಾನ ಮತ್ತು ಮಾರುಕಟ್ಟೆ",
    featBadge: "🌾 ರೈತರಿಗಾಗಿ ವಿಶೇಷವಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ",
    featHeading: "ಬೆಳೆಗಳನ್ನು ರಕ್ಷಿಸಿ ಮತ್ತು ಗರಿಷ್ಠ ಇಳುವರಿ ಪಡೆಯಿರಿ",
    featSubheading: "ನಿಮ್ಮ ಮೊಬೈಲ್ ಮೂಲಕ ಕೃಷಿ ಸಮಸ್ಯೆಗಳನ್ನು ನಿವಾರಿಸಲು ಸರಳ ಮತ್ತು ಉಪಯುಕ್ತ ಸಾಧನಗಳು.",
    f1Title: "Instant Plant Disease Detection",
    f1Sub: "ತಕ್ಷಣದ ಬೆಳೆ ರೋಗ ಪತ್ತೆ",
    f1Desc: "ರೋಗಪೀಡಿತ ಎಲೆಯ ಫೋಟೋ ತೆಗೆಯಿರಿ. Gemini Vision AI ಶಿಲೀಂಧ್ರ, ಬ್ಯಾಕ್ಟೀರಿಯಾ ಮತ್ತು ಕೀಟ ಬಾಧೆಗಳನ್ನು ತಕ್ಷಣ ಪತ್ತೆ ಮಾಡುತ್ತದೆ.",
    f2Title: "Precision Fertilizer Dosage",
    f2Sub: "ಸರಿಯಾದ ಗೊಬ್ಬರದ ಪ್ರಮಾಣ",
    f2Desc: "ಅನಗತ್ಯ ಖರ್ಚು ತಪ್ಪಿಸಿ. ನಿಮ್ಮ ಮಣ್ಣಿನ ಪ್ರಕಾರ ಮತ್ತು ಬೆಳೆಗೆ ಸೂಕ್ತವಾದ N-P-K ಗೊಬ್ಬರಗಳ ಪ್ರಮಾಣ ತಿಳಿಯಿರಿ.",
    f3Title: "Soil-Smart Crop Advisory",
    f3Sub: "ಸೂಕ್ತ ಬೆಳೆ ಶಿಫಾರಸು",
    f3Desc: "ನಿಮ್ಮ ಮಣ್ಣಿನ ಪೋಷಕಾಂಶಗಳು ಮತ್ತು ಮಳೆಯ ಪ್ರಮಾಣ ಆಧರಿಸಿ ಹೆಚ್ಚು ಇಳುವರಿ ನೀಡುವ ಬೆಳೆಗಳನ್ನು ಶಿಫಾರಸು ಮಾಡುತ್ತದೆ.",
    f4Title: "Multilingual Voice Assistant",
    f4Sub: "ಧ್ವನಿ ಆಧಾರಿತ ಕೃಷಿ ಸಹಾಯ",
    f4Desc: "ಫೋನ್‌ನಲ್ಲಿ ಕನ್ನಡದಲ್ಲಿ ಮಾತನಾಡಿ ಕೃಷಿ ಪ್ರಶ್ನೆಗಳನ್ನು ಕೇಳಿ ಮತ್ತು ಧ್ವನಿ ಮೂಲಕವೇ ಉತ್ತರಗಳನ್ನು ಪಡೆಯಿರಿ."
  },
  hindi: {
    code: "hi",
    name: "हिन्दी (Hindi)",
    speechLang: "hi-IN",
    navHome: "Home",
    navBlog: "Blog",
    navCommunity: "Community",
    navWeather: "Weather",
    navMarket: "Market Tracker",
    navLanguages: "Languages",
    btnDiseasePredict: "Disease Predict",
    btnFertilization: "Fertilization",
    btnRecommend: "Recommend",
    heroBadge: "AI कृषि डॉक्टर • मुफ्त फसल रोग जांच",
    heroTitle1: "Protect Your Crops from",
    heroTitle2: "Pests & Diseases Instantly.",
    heroSubtitle: "अपनी फसल के पत्तों की फोटो अपलोड करें। हमारा AI सेकंडों में बीमारी की पहचान करके सही उपचार और जैविक कीटनाशक हिंदी में बताएगा।",
    step1Title: "1. Take Photo",
    step1Desc: "फोटो लें",
    step2Title: "2. AI Scans",
    step2Desc: "रोग पहचान",
    step3Title: "3. Get Cure",
    step3Desc: "उपाय पाएं",
    btnScanDisease: "Scan Crop Disease Now",
    btnCropAdvisory: "Crop Advisory",
    shortDisease: "Disease Doctor",
    shortDiseaseDesc: "फसल रोग पहचान",
    shortCrop: "Crop Recommendation",
    shortCropDesc: "उचित फसल सलाह",
    shortFertilizer: "Fertilizer Advisory",
    shortFertilizerDesc: "खाद की सही मात्रा",
    shortWeather: "Weather & Market",
    shortWeatherDesc: "मौसम और मंडी भाव",
    featBadge: "🌾 विशेष रूप से किसानों के लिए डिज़ाइन किया गया",
    featHeading: "अपनी फसलों की सुरक्षा करें और अधिक पैदावार पाएं",
    featSubheading: "स्मार्टफोन से खेती की समस्याओं को हल करने के आसान और सटीक डिजिटल टूल्स।",
    f1Title: "Instant Plant Disease Detection",
    f1Sub: "तुरंत फसल रोग जांच",
    f1Desc: "पत्ते की फोटो खींचें और AI से तुरंत फंगल, बैक्टीरियल व कीट संक्रमण का पता लगाएं।",
    f2Title: "Precision Fertilizer Dosage",
    f2Sub: "सटीक उर्वरक मात्रा",
    f2Desc: "अतिरिक्त खर्च से बचें। अपनी मिट्टी और फसल के लिए सही N-P-K खाद का अनुपात जानें।",
    f3Title: "Soil-Smart Crop Advisory",
    f3Sub: "मिट्टी अनुसार फसल सलाह",
    f3Desc: "मिट्टी के पोषक तत्वों और मौसम के आधार पर सबसे अधिक मुनाफा देने वाली फसल चुनें।",
    f4Title: "Multilingual Voice Assistant",
    f4Sub: "वॉइस कृषि सहायक",
    f4Desc: "हिंदी में बोलकर खेती के सवाल पूछें और आवाज में ही तुरंत समाधान सुनें।"
  },
  english: {
    code: "en",
    name: "English",
    speechLang: "en-US",
    navHome: "Home",
    navBlog: "Blog",
    navCommunity: "Community",
    navWeather: "Weather",
    navMarket: "Market Tracker",
    navLanguages: "Languages",
    btnDiseasePredict: "Disease Predict",
    btnFertilization: "Fertilization",
    btnRecommend: "Recommend",
    heroBadge: "AI Crop Doctor • Free Plant Health Check",
    heroTitle1: "Protect Your Crops from",
    heroTitle2: "Pests & Diseases Instantly.",
    heroSubtitle: "Take or upload a leaf photo. Our AI identifies infections in seconds and gives you simple remedies, chemical spray dosages, and organic solutions.",
    step1Title: "1. Take Photo",
    step1Desc: "Upload Leaf",
    step2Title: "2. AI Scans",
    step2Desc: "Detect Disease",
    step3Title: "3. Get Cure",
    step3Desc: "Treatment Guide",
    btnScanDisease: "Scan Crop Disease Now",
    btnCropAdvisory: "Crop Advisory",
    shortDisease: "Disease Doctor",
    shortDiseaseDesc: "Plant Disease Doctor",
    shortCrop: "Crop Recommendation",
    shortCropDesc: "Soil-Smart Advisory",
    shortFertilizer: "Fertilizer Advisory",
    shortFertilizerDesc: "Nutrient Dosage",
    shortWeather: "Weather & Market",
    shortWeatherDesc: "Live Weather & Mandi",
    featBadge: "🌾 Designed Specifically for Farmers",
    featHeading: "Protect Your Crops & Maximize Harvest Yield",
    featSubheading: "Simple, practical, and accessible tools created to solve day-to-day farming challenges.",
    f1Title: "Instant Plant Disease Detection",
    f1Sub: "Visual AI Plant Doctor",
    f1Desc: "Upload a photo of any unhealthy leaf. Gemini Vision AI identifies fungal, bacterial, and pest attacks in seconds.",
    f2Title: "Precision Fertilizer Dosage",
    f2Sub: "Optimal Nutrient Control",
    f2Desc: "Avoid excess chemical costs. Get exact N-P-K fertilizer and organic compost dosages customized for your soil.",
    f3Title: "Soil-Smart Crop Advisory",
    f3Sub: "High Yield Crop Choices",
    f3Desc: "Machine learning models analyze your soil nitrogen, phosphorus, potassium, and climate to suggest the best crops.",
    f4Title: "Multilingual Voice Assistant",
    f4Sub: "Hands-Free Voice Helper",
    f4Desc: "Ask farming questions by speaking into your phone and listen to spoken advice without typing."
  },
  telugu: {
    code: "te",
    name: "తెలుగు (Telugu)",
    speechLang: "te-IN",
    navHome: "Home",
    navBlog: "Blog",
    navCommunity: "Community",
    navWeather: "Weather",
    navMarket: "Market Tracker",
    navLanguages: "Languages",
    btnDiseasePredict: "Disease Predict",
    btnFertilization: "Fertilization",
    btnRecommend: "Recommend",
    heroBadge: "AI రైతు డాక్టర్ • ఉచిత పంట తెగుళ్ల గుర్తింపు",
    heroTitle1: "Protect Your Crops from",
    heroTitle2: "Pests & Diseases Instantly.",
    heroSubtitle: "మీ పంట ఆకుల ఫోటో తీయండి. మా AI క్షణాల్లో తెగుళ్లను గుర్తించి మందుల మోతాదు మరియు నివారణ పద్ధతులను తెలుగులో అందిస్తుంది.",
    step1Title: "1. Take Photo",
    step1Desc: "ఫోటో తీయండి",
    step2Title: "2. AI Scans",
    step2Desc: "తెగులు గుర్తింపు",
    step3Title: "3. Get Cure",
    step3Desc: "నివారణ మార్గం",
    btnScanDisease: "Scan Crop Disease Now",
    btnCropAdvisory: "Crop Advisory",
    shortDisease: "Disease Doctor",
    shortDiseaseDesc: "పంట తెగులు గుర్తింపు",
    shortCrop: "Crop Recommendation",
    shortCropDesc: "సరైన పంట సలహా",
    shortFertilizer: "Fertilizer Advisory",
    shortFertilizerDesc: "ఎరువుల సరైన మోతాదు",
    shortWeather: "Weather & Market",
    shortWeatherDesc: "వాతావరణం మరియు మార్కెట్",
    featBadge: "🌾 ప్రత్యేకంగా రైతుల కోసం రూపొందించబడింది",
    featHeading: "మీ పంటలను రక్షించండి మరియు అధిక దిగుబడిని పొందండి",
    featSubheading: "స్మార్ట్‌ఫోన్ ద్వారా వ్యవసాయ సమస్యలను సులభంగా పరిష్కరించే డిజిటల్ సాధనాలు.",
    f1Title: "Instant Plant Disease Detection",
    f1Sub: "తక్షణ పంట తెగుళ్ల గుర్తింపు",
    f1Desc: "ఆకు ఫోటోను అప్‌లోడ్ చేసి క్షణాల్లో సరైన పురుగుమందులు మరియు నివారణ మార్గాలు తెలుసుకోండి.",
    f2Title: "Precision Fertilizer Dosage",
    f2Sub: "సరైన ఎరువుల మోతాదు",
    f2Desc: "అనవసర ఖర్చులను నివారించండి. మీ నేల స్వభావానికి సరిపోయే N-P-K ఎరువుల మోతాదు తెలుసుకోండి.",
    f3Title: "Soil-Smart Crop Advisory",
    f3Sub: "నేలకు సరిపడే పంట సలహా",
    f3Desc: "మీ నేలలోని పోషకాలు మరియు వర్షపాతం ఆధారంగా అధిక దిగుబడినిచ్చే పంటలను ఎంచుకోండి.",
    f4Title: "Multilingual Voice Assistant",
    f4Sub: "వాయిస్ వ్యవసాయ సహాయకుడు",
    f4Desc: "తెలుగులో మాట్లాడి వ్యవసాయ సందేహాలను అడగండి మరియు వాయిస్ ద్వారా సమాధానాలు వినండి."
  },
  tamil: {
    code: "ta",
    name: "தமிழ் (Tamil)",
    speechLang: "ta-IN",
    navHome: "Home",
    navBlog: "Blog",
    navCommunity: "Community",
    navWeather: "Weather",
    navMarket: "Market Tracker",
    navLanguages: "Languages",
    btnDiseasePredict: "Disease Predict",
    btnFertilization: "Fertilization",
    btnRecommend: "Recommend",
    heroBadge: "AI பயிர் மருத்துவர் • இலவச பயிர் நோய் கண்டறிதல்",
    heroTitle1: "Protect Your Crops from",
    heroTitle2: "Pests & Diseases Instantly.",
    heroSubtitle: "பாதிக்கப்பட்ட பயிர் இலையின் புகைப்படத்தை பதிவேற்றுங்கள். எங்கள் AI உடனடியாக நோயைக் கண்டறிந்து தீர்வு மற்றும் மருந்துகளை தமிழில் வழங்கும்.",
    step1Title: "1. Take Photo",
    step1Desc: "புகைப்படம் எடுங்கள்",
    step2Title: "2. AI Scans",
    step2Desc: "நோய் கண்டறிதல்",
    step3Title: "3. Get Cure",
    step3Desc: "தீர்வு பெறுங்கள்",
    btnScanDisease: "Scan Crop Disease Now",
    btnCropAdvisory: "Crop Advisory",
    shortDisease: "Disease Doctor",
    shortDiseaseDesc: "பயிர் நோய் கண்டறிதல்",
    shortCrop: "Crop Recommendation",
    shortCropDesc: "பயிர் ஆலோசனை",
    shortFertilizer: "Fertilizer Advisory",
    shortFertilizerDesc: "உர அளவு வழிகாட்டி",
    shortWeather: "Weather & Market",
    shortWeatherDesc: "வானிலை & சந்தை விலை",
    featBadge: "🌾 விவசாயிகளுக்காக வடிவமைக்கப்பட்டது",
    featHeading: "பயிர்களை பாதுகாத்து அதிக விளைச்சலை பெறுங்கள்",
    featSubheading: "விவசாய பிரச்சினைகளை எளிய முறையில் தீர்க்க உதவும் நவீன தொழில்நுட்பம்.",
    f1Title: "Instant Plant Disease Detection",
    f1Sub: "உடனடி பயிர் நோய் கண்டறிதல்",
    f1Desc: "இலையின் புகைப்படத்தை எடுத்து உடனடியாக பூஞ்சை, பாக்டீரியா தாக்குதல்களை கண்டறியுங்கள்.",
    f2Title: "Precision Fertilizer Dosage",
    f2Sub: "சரியான உர அளவு",
    f2Desc: "உங்கள் மண்ணின் வகைக்கு ஏற்ற N-P-K உரங்களின் சரியான அளவை பெற்று பணத்தை சேமிக்கவும்.",
    f3Title: "Soil-Smart Crop Advisory",
    f3Sub: "மண்ணுக்கேற்ற பயிர் தேர்வு",
    f3Desc: "உங்கள் மண்ணின் சத்துக்களுக்கு ஏற்ப அதிக லாபம் தரும் பயிர்களை கண்டறியுங்கள்.",
    f4Title: "Multilingual Voice Assistant",
    f4Sub: "குரல் வழி விவசாய உதவியாளர்",
    f4Desc: "தமிழில் பேசி விவசாய கேள்விகளை கேட்டு குரல் வழியாகவே பதில்களை பெறுங்கள்."
  }
};

export const LanguageProvider = ({ children }) => {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('agrosage_lang') || 'marathi';
  });

  const changeLanguage = (langKey) => {
    const key = langKey.toLowerCase();
    if (translations[key]) {
      setCurrentLang(key);
      localStorage.setItem('agrosage_lang', key);
    }
  };

  const t = (key) => {
    const langData = translations[currentLang] || translations.marathi;
    return langData[key] || translations.marathi[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLang, changeLanguage, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
